sl3

diff --git a/.github/workflows/1_auto_approve.yml b/.github/workflows/1_auto_approve.yml
--- a/.github/workflows/1_auto_approve.yml
+++ b/.github/workflows/1_auto_approve.yml
@@ -16,8 +16,24 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Verify Modified Files Step
-      if: github.mergeable_state != 'draft'
+      # if: github.mergeable_state != 'draft'
       run: |
+
+          # Make sure this PR is not a "Draft PR"
+
+          if 
+            echo ${{ github.mergeable_state }} | grep -i draft 
+          then
+            echo
+            echo "  ERROR: This PR is Draft PR. No automation work can be done further"
+            echo
+            exit 6
+          else
+            echo
+            echo  " CONFIRMED: This PR is not a Draft PR. Keep automation steps."
+            echo
+          fi
+
           # List of the dirs, modifications of which could be Automatically Approved
           #   LIST_OF_ONLY_DIRS_TO_BE_MODIFIED="dir1 dir2 dir3 ..."
           LIST_OF_ONLY_DIRS_TO_BE_MODIFIED="dir1 dir2"
@@ -63,7 +79,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Auto Approve Step
-      if: success() && github.mergeable_state != 'draft'
+      # if: success() && github.mergeable_state != 'draft'
       uses: hmarr/auto-approve-action@v2.0.0
       with:
         github-token: "${{ secrets.GITHUB_TOKEN }}"
@@ -73,7 +89,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Auto Rebase and Merge Step 
-        if: success()
+        # if: success()
         uses: docker://ppnp/nolabelautomerge:latest
         env:
           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
@@ -84,7 +100,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Delete the Branch after Auto Rebase and Merge Step
-      if: success()
+      # if: success()
       run: |
 
           curl --request DELETE \
@@ -102,7 +118,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Slack Notification
-      if: success()
+      # if: success()
       uses: docker://ppnp/actions-slack-notify:latest
       env:
         SLACK_CHANNEL: test-test
