upd ref to 1 specific value

diff --git a/.github/workflows/main_auto_flow.yml b/.github/workflows/main_auto_flow.yml
--- a/.github/workflows/main_auto_flow.yml
+++ b/.github/workflows/main_auto_flow.yml
@@ -1,3 +1,5 @@
+# https://github.com/marketplace/actions/wait-for-check
+
 name: Main Auto Flow
 
 on: 
@@ -13,30 +15,26 @@ jobs:
   main_job:
     runs-on: ubuntu-latest
     steps:
-      - name: this step should depend on Status
-        run: |
-             echo
-             echo  "Status of the Job:   OK"
-             echo
-
       - name: Wait for build to succeed
         uses: fountainhead/action-wait-for-check@v1.0.0
         id: wait-for-build
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           checkName: s_or_f_job
-          ref: github.event.pull_request.head.sha || github.sha
+          # ref: github.event.pull_request.head.sha || github.sha
+          ref: github.sha
 
-      - name: Do something with a passing build
+      - name: What if it's SUCCESS?
         if: steps.wait-for-build.outputs.conclusion == 'success'
         run: |
              echo
              echo  "I can see that status of the Additional Job:   OK"
              echo
 
-      - name: Do something with a failing build
+      - name: What if it's FAIL?
         if: steps.wait-for-build.outputs.conclusion == 'failure'
         run: |
              echo
-             echo  "I can see that status of the Additional Job:   OK"
+             echo  "I can see that status of the Additional Job:   FAIL"
              echo
+             exit 4
